return {
    NotifyERRORTitle = { fg = "#f7768e", bg = "none" },
    NotifyERRORBorder = { fg = "#f7768e", bg = "none" },
    NotifyERRORIcon = { fg = "#f7768e", bg = "none" },
    NotifyWARNTitle = { fg = "#e0af68", bg = "none" },
    NotifyWARNBorder = { fg = "#e0af68", bg = "none" },
    NotifyWARNIcon = { fg = "#e0af68", bg = "none" },
    NotifyINFOTitle = { fg = "#7dcfff", bg = "none" },
    NotifyINFOBorder = { fg = "#7dcfff", bg = "none" },
    NotifyINFOIcon = { fg = "#7dcfff", bg = "none" },
    NotifyDEBUGTitle = { fg = "#8B8B8B", bg = "none" },
    NotifyDEBUGBorder = { fg = "#8B8B8B", bg = "none" },
    NotifyDEBUGIcon = { fg = "#8B8B8B", bg = "none" },
    NotifyTRACETitle = { fg = "#D484FF", bg = "none" },
    NotifyTRACEBorder = { fg = "#4F3552", bg = "none" },
    NotifyTRACEIcon = { fg = "#D484FF", bg = "none" },
}
