local theme = require("themes." .. vim.g.nv_theme).base_16
local colors = require("themes." .. vim.g.nv_theme).base_30

return {
    TSAnnotation = { fg = theme.base0F },
    TSAttribute = { fg = theme.base0A },
    TSCharacter = { fg = theme.base08 },
    TSConstructor = { fg = theme.base0C },
    TSConstBuiltin = { fg = theme.base09 },
    TSConstMacro = { fg = theme.base08 },
    TSError = { fg = theme.base08 },
    TSException = { fg = theme.base08 },
    TSFloat = { fg = theme.base09 },
    TSKeyword = { fg = theme.base0E },
    TSKeywordFunction = { fg = theme.base0E },
    TSKeywordReturn = { fg = theme.base0E },
    TSFunction = { fg = theme.base0D },
    TSFuncBuiltin = { fg = theme.base0D },
    TSFuncMacro = { fg = theme.base08 },
    TSKeywordOperator = { fg = theme.base0E },
    TSMethod = { fg = theme.base0D },
    TSNamespace = { fg = theme.base08 },
    TSNone = { fg = theme.base05 },
    TSParameter = { fg = theme.base08 },
    TSParameterReference = { fg = theme.base05 },
    TSPunctBracket = { fg = theme.base0F },
    TSPunctDelimiter = { fg = theme.base0F },
    TSPunctSpecial = { fg = theme.base08 },
    TSStringRegex = { fg = theme.base0C },
    TSStringEscape = { fg = theme.base0C },
    TSSymbol = { fg = theme.base0B },
    TSTagDelimiter = { fg = theme.base0F },
    TSText = { fg = theme.base05 },
    TSEmphasis = { fg = theme.base09 },
    TSStrike = { fg = theme.base00 },
    TSLiteral = { fg = theme.base09 },
    TSURI = { fg = theme.base09 },
    TSTypeBuiltin = { fg = theme.base0A },
    TSVariableBuiltin = { fg = theme.base09 },
    TSVariable = { fg = theme.base05 },
    TSDefinition = { fg = theme.base04 },
    TSDefinitionUsage = { fg = theme.base04 },
    TSField = { fg = theme.base0D },
    TSFieldKey = { fg = theme.base08 },
    TSProperty = { fg = theme.base08 },
}
